version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: ${DB_DATABASE_NAME:?err}
      MYSQL_USER: ${DB_USERNAME:?err}
      MYSQL_PASSWORD: ${DB_PASSWORD:?err}
    ports:
      - 3306:3306
    
  samba:
    image: laslabs/alpine-samba-dc:0.1.0
    cap_add:
      - SYS_ADMIN
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      SAMBA_DC_REALM: dc.localdomain
      SAMBA_DC_DOMAIN: DC
      SAMBA_DC_ADMIN_PASSWD: ${LDAP_ADMIN_PASSWD:?err}
      SAMBA_DC_DNS_BACKEND: SAMBA_INTERNAL
    ports:
      - 389:389
      - 389:389/udp

  wait:
    image: willwill/wait-for-it:latest